### PR TITLE
Add the ability to horizontally extrapolate basins and fields one at a time

### PR DESCRIPTION
**Pull request by xylar**
This is useful for performing extrapolation at a single point in time efficiently (e.g. if topography is changing in time).

The `extrap_horiz` function has been broken into multiple helper functions (setup, extrapolating basins, extrapolating the open ocean, and combining the basins) for clarity.

New config options and command-line flags have been added to control this new functionality.

### CODE REVIEW

**Comment by xylar** [comment]
## Testing

I tested this on 8 nodes on Cori-Haswell using the following config file and job script:

`config.ukesm1-0-ll_2015`:
``` cfg
[parallel]
tasks = 32


[observations]
compute = False


[output]
## Options related to the time and depth indices to include in the analysis

# min/max time index (-1 for the end of the time variable)
tIndexMin = 20
tIndexMax = 20


[model]
## Config options related to the model to extrapolate forcing for

compute = True

# The name of the model
name = UKESM1-0-LL

# Input files
temperatureFileName = ukesm1-0-ll/thetao_annual_UKESM1-0-LL_ssp585_r4i1p1f2_199501-230012.nc
salinityFileName = ukesm1-0-ll/so_annual_UKESM1-0-LL_ssp585_r4i1p1f2_199501-230012.nc

# Variable names
lon = lon
lat = lat
z = lev
time = time
temperature = thetao
salinity = so
z_bnds = lev_bnds

# Output folder
folder = 2015
```

`job_script_ukesm_2015.bash`:
``` bash
#!/bin/bash -l
# comment out if using debug queue
#SBATCH --partition=regular
# comment in to get premium queue
##SBATCH --qos=premium
# comment in to get the debug queue
##SBATCH --partition=debug
# change number of nodes to change the number of parallel tasks
# (anything between 1 and the total number of tasks to run)
#SBATCH --nodes=8
#SBATCH --time=1:00:00
#SBATCH --account=m1795
#SBATCH --job-name=ukesm1-0-ll_2015
#SBATCH --output=ukesm1-0-ll/2015/ismip6.o%j
#SBATCH --error=ukesm1-0-ll/2015/ismip6.e%j
#SBATCH -L SCRATCH
#SBATCH -C haswell

export OMP_NUM_THREADS=1

source /global/homes/x/xylar/miniconda3/etc/profile.d/conda.sh
conda activate ismip6
export HDF5_USE_FILE_LOCKING=FALSE

export log_dir=ukesm1-0-ll/2015/logs
mkdir $log_dir

echo "setup"
srun -N 1 -n 1 -c 32 ismip6_ocean_forcing config.ukesm1-0-ll_2015 \
  --model_basin=none

echo "extrapolate basins"
for field in temperature salinity
do
  echo "$field basins 1-8"
  for basin in $(seq 1 8)
  do
    srun -N 1 -n 1 -c 32 ismip6_ocean_forcing config.ukesm1-0-ll_2015 \
      --model_field=$field --model_basin=$basin \
      >& ${log_dir}/ukesm1-0-ll_2015_${field}_basin_${basin}.log & 
  done
  wait

  echo "$field basins 9-16"
  for basin in $(seq 9 16)
  do
    srun -N 1 -n 1 -c 32 ismip6_ocean_forcing config.ukesm1-0-ll_2015 \
      --model_field=$field --model_basin=$basin \
      >& ${log_dir}/ukesm1-0-ll_2015_${field}_basin_${basin}.log & 
  done
  wait
done

echo "extrapolate open ocean"
for field in temperature salinity
do
    srun -N 1 -n 1 -c 32 ismip6_ocean_forcing config.ukesm1-0-ll_2015 \
      --model_field=$field --model_basin=open_ocean \
      >& ${log_dir}/ukesm1-0-ll_2015_${field}_open_ocean.log & 
done
wait

echo "combine basins"
srun -N 1 -n 1 -c 32 ismip6_ocean_forcing config.ukesm1-0-ll_2015 \
  --model_basin=none --model_combine_basins
```
The 34 basin extrapolation jobs would ideally all be run at once on 34 nodes rather than 8.

**Comment by xylar** [comment]
Here would be a simpler version of the same job script but running on 34 nodes:
``` bash
#!/bin/bash -l
# comment out if using debug queue
#SBATCH --partition=regular
# comment in to get premium queue
##SBATCH --qos=premium
# comment in to get the debug queue
##SBATCH --partition=debug
# change number of nodes to change the number of parallel tasks
# (anything between 1 and the total number of tasks to run)
#SBATCH --nodes=34
#SBATCH --time=1:00:00
#SBATCH --account=m1795
#SBATCH --job-name=ukesm1-0-ll_2015
#SBATCH --output=ukesm1-0-ll/2015/ismip6.o%j
#SBATCH --error=ukesm1-0-ll/2015/ismip6.e%j
#SBATCH -L SCRATCH
#SBATCH -C haswell

export OMP_NUM_THREADS=1

source /global/homes/x/xylar/miniconda3/etc/profile.d/conda.sh
conda activate ismip6
export HDF5_USE_FILE_LOCKING=FALSE

export log_dir=ukesm1-0-ll/2015/logs
mkdir $log_dir

echo "setup"
srun -N 1 -n 1 -c 32 ismip6_ocean_forcing config.ukesm1-0-ll_2015 \
  --model_basin=none

echo "extrapolate basins"
for field in temperature salinity
do
  for basin in $(seq 1 16)
  do
    srun -N 1 -n 1 -c 32 ismip6_ocean_forcing config.ukesm1-0-ll_2015 \
      --model_field=$field --model_basin=$basin \
      >& ${log_dir}/ukesm1-0-ll_2015_${field}_basin_${basin}.log & 
  done
  srun -N 1 -n 1 -c 32 ismip6_ocean_forcing config.ukesm1-0-ll_2015 \
      --model_field=$field --model_basin=open_ocean \
      >& ${log_dir}/ukesm1-0-ll_2015_${field}_open_ocean.log & 
done
wait

echo "combine basins"
srun -N 1 -n 1 -c 32 ismip6_ocean_forcing config.ukesm1-0-ll_2015 \
  --model_basin=none --model_combine_basins
```

**Comment by hollyhan** [comment]
Thanks for adding the parallel-computing capability to the package, @xylar!

I've tested the code in the interactive mode `salloc` by copying and pasting the commands in the job script, and I get `FileNotFound` error at the very first command that I run from the directory `/global/cscratch1/sd/hollyhan/ismip6-ocean-forcing/bedmap2/ukesm1-0-ll/2015/`:

 ``` echo "setup"
srun -N 1 -n 1 -c 32 ismip6_ocean_forcing config.ukesm1-0-ll_2015 \
  --model_basin=none

FileNotFoundError: [Errno 2] No such file or directory: b'/global/cscratch1/sd/hollyhan/ismip6-ocean-forcing/bedmap2/ukesm1-0-ll/2015/ukesm1-0-ll/thetao_annual_UKESM1-0-LL_ssp585_r4i1p1f2_199501-230012.nc'
```

The data file `thetao_annual_UKESM1-0-LL_ssp585_r4i1p1f2_199501-230012.nc'` is kept in the directory `/global/cscratch1/sd/hollyhan/ismip6-ocean-forcing/bedmap2/ukesm1-0-ll/2015/`, not in  `/global/cscratch1/sd/hollyhan/ismip6-ocean-forcing/bedmap2/ukesm1-0-ll/2015/ukesm1-0-ll/`.

Alternatively, running the same `srun` command in the directory ``/global/cscratch1/sd/hollyhan/ismip6-ocean-forcing/bedmap2` also does not work because now it can't find the config file `config.ukesm1-0-ll_2015`, since the config file is  in the directory `/global/cscratch1/sd/hollyhan/ismip6-ocean-forcing/bedmap2/ukesm1-0-ll/2015/`

Do you think there should be something added to point to the correct data path? Or am I running the code from a wrong directory? 

Thanks!! 
Holly

**Comment by xylar** [comment]
@hollyhan, thanks for testing!

The idea is to run ismip6_ocean_forcing` out of the common directory where all the folders are found (`bedmap2`, `ukesm-0-ll`, `obs`, etc., so 2 directories up from where you're running.

The file `thetao_annual_UKESM1-0-LL_ssp585_r4i1p1f2_199501-230012.nc` should be in the `ukesm1-0-ll` directory but not in `ukesm1-0-ll/2015`, which is I think what you were saying above but maybe that was just a wrong directory name.

So you should be in `/global/cscratch1/sd/hollyhan/ismip6-ocean-forcing/bedmap2/`.  In my example above, I had copied the config file into that directory, but I don't think you need to do that.  You can just use the one directly out of the `ukesm1-0-ll/2015` directory:
```
srun -N 1 -n 1 -c 32 ismip6_ocean_forcing ukesm1-0-ll/2015/config.ukesm1-0-ll --model_basin=none
```

Sorry for not explaining that very well before.  Hopefully, this helps.

**Comment by hollyhan** [comment]
Great! Thanks for the clarification, @xylar!

You are right that the data `thetao_annual_UKESM1-0-LL_ssp585_r4i1p1f2_199501-230012.nc` is in the `ukesm1-0-ll` directory, not in `ukesm1-0-ll/2015`. 

I copied over the config file to the directory where I was running the command from (`/global/cscratch1/sd/hollyhan/ismip6-ocean-forcing/bedmap2/`), and everything worked fine up to the last command line where I get an error related to HPF: 

```
(ismip6) hollyhan@nid00215:/global/cscratch1/sd/hollyhan/ismip6-ocean-forcing/bedmap2> srun -N 1 -n 1 -c 32 ismip6_ocean_forcing config.ukesm1-0-ll_2015   --model_basin=none --model_combine_basins
Extrapolate UKESM1-0-LL model results...
Traceback (most recent call last):
  File "/global/homes/h/hollyhan/miniconda3/envs/ismip6/lib/python3.10/site-packages/xarray/backends/file_manager.py", line 199, in _acquire_with_cache_info
    file = self._cache[self._key]
  File "/global/homes/h/hollyhan/miniconda3/envs/ismip6/lib/python3.10/site-packages/xarray/backends/lru_cache.py", line 53, in __getitem__
    value = self._cache[key]
KeyError: [<class 'netCDF4._netCDF4.Dataset'>, ('/global/cscratch1/sd/hollyhan/ismip6-ocean-forcing/bedmap2/ukesm1-0-ll/2015/progress_salinity/basin15.nc',), 'r', (('clobber', True), ('diskless', False), ('format', 'NETCDF4'), ('persist', False))]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/global/homes/h/hollyhan/miniconda3/envs/ismip6/bin/ismip6_ocean_forcing", line 33, in <module>
    sys.exit(load_entry_point('ismip6-ocean-forcing', 'console_scripts', 'ismip6_ocean_forcing')())
  File "/global/u1/h/hollyhan/ismip6-antarctic-ocean-forcing/master/ismip6_ocean_forcing/__main__.py", line 66, in main
    extrapolate_model(config)
  File "/global/u1/h/hollyhan/ismip6-antarctic-ocean-forcing/master/ismip6_ocean_forcing/model/extrap.py", line 39, in extrapolate_model
    _extrap_model(config, modelFolder)
  File "/global/u1/h/hollyhan/ismip6-antarctic-ocean-forcing/master/ismip6_ocean_forcing/model/extrap.py", line 76, in _extrap_model
    extrap_horiz(config, inFileName, outFileName, fieldName, bedFileName,
  File "/global/u1/h/hollyhan/ismip6-antarctic-ocean-forcing/master/ismip6_ocean_forcing/extrap/horiz.py", line 77, in extrap_horiz
    combine_basins(outFileName, fieldName, bedmap2FileName,
  File "/global/u1/h/hollyhan/ismip6-antarctic-ocean-forcing/master/ismip6_ocean_forcing/extrap/horiz.py", line 251, in combine_basins
    ds = xarray.open_dataset(progressFileName)
  File "/global/homes/h/hollyhan/miniconda3/envs/ismip6/lib/python3.10/site-packages/xarray/backends/api.py", line 495, in open_dataset
    backend_ds = backend.open_dataset(
  File "/global/homes/h/hollyhan/miniconda3/envs/ismip6/lib/python3.10/site-packages/xarray/backends/netCDF4_.py", line 553, in open_dataset
    store = NetCDF4DataStore.open(
  File "/global/homes/h/hollyhan/miniconda3/envs/ismip6/lib/python3.10/site-packages/xarray/backends/netCDF4_.py", line 382, in open
    return cls(manager, group=group, mode=mode, lock=lock, autoclose=autoclose)
  File "/global/homes/h/hollyhan/miniconda3/envs/ismip6/lib/python3.10/site-packages/xarray/backends/netCDF4_.py", line 330, in __init__
    self.format = self.ds.data_model
  File "/global/homes/h/hollyhan/miniconda3/envs/ismip6/lib/python3.10/site-packages/xarray/backends/netCDF4_.py", line 391, in ds
    return self._acquire()
  File "/global/homes/h/hollyhan/miniconda3/envs/ismip6/lib/python3.10/site-packages/xarray/backends/netCDF4_.py", line 385, in _acquire
    with self._manager.acquire_context(needs_lock) as root:
  File "/global/homes/h/hollyhan/miniconda3/envs/ismip6/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/global/homes/h/hollyhan/miniconda3/envs/ismip6/lib/python3.10/site-packages/xarray/backends/file_manager.py", line 187, in acquire_context
    file, cached = self._acquire_with_cache_info(needs_lock)
  File "/global/homes/h/hollyhan/miniconda3/envs/ismip6/lib/python3.10/site-packages/xarray/backends/file_manager.py", line 205, in _acquire_with_cache_info
    file = self._opener(*self._args, **kwargs)
  File "src/netCDF4/_netCDF4.pyx", line 2307, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 1925, in netCDF4._netCDF4._ensure_nc_success
OSError: [Errno -101] NetCDF: HDF error: b'/global/cscratch1/sd/hollyhan/ismip6-ocean-forcing/bedmap2/ukesm1-0-ll/2015/progress_salinity/basin15.nc'
srun: error: nid00215: task 0: Exited with exit code 1
srun: launch/slurm: _step_signal: Terminating StepId=55215893.38


```

**Comment by xylar** [comment]
@hollyhan, does that file (`ukesm1-0-ll/2015/progress_salinity/basin15.nc`) exist?  If so, can you run `ncdump -h` on it to make sure it's not corrupted somehow?

Could it be a file lock problem?  Did you run:
```
export HDF5_USE_FILE_LOCKING=FALSE
```
as part of your procedure like I have in my job script?

**Comment by hollyhan** [comment]
Yes, I exported `export HDF5_USE_FILE_LOCKING=FALSE`, and the file exists in the directory. 

When I do `ncdump -h` on `basin15.nc`, I get `NetCDF: HDF error`, whereas ncdump -h works fine on other files (e.g,. `basin14.nc`).

**Comment by xylar** [comment]
It looks like that file got corrupted.  Was there any error message in the log file associated with that run:
```
ukesm1-0-ll/2015/logs/ukesm1-0-ll_2015_salinity_basin15.log
```
?

**Comment by hollyhan** [comment]
@xylar,

 `vi ukesm1-0-ll/2015/logs/ukesm1-0-ll_2015_salinity_basin15.log` shows me no error in the log file - all I see is `Extrapolate UKESM1-0-LL model results...
  Done.`

I tried to run the commands from scratch and still get the same hdf error - below is the copy and paste of my terminal window. 

```
(ismip6) hollyhan@nid00195:/global/cscratch1/sd/hollyhan/ismip6-ocean-forcing/bedmap2> export OMP_NUM_THREADS=1
(ismip6) hollyhan@nid00195:/global/cscratch1/sd/hollyhan/ismip6-ocean-forcing/bedmap2> source ~/miniconda3/etc/profile.d/conda.sh
(ismip6) hollyhan@nid00195:/global/cscratch1/sd/hollyhan/ismip6-ocean-forcing/bedmap2> conda activate ismip6
(ismip6) hollyhan@nid00195:/global/cscratch1/sd/hollyhan/ismip6-ocean-forcing/bedmap2> export HDF5_USE_FILE_LOCKING=FALSE
(ismip6) hollyhan@nid00195:/global/cscratch1/sd/hollyhan/ismip6-ocean-forcing/bedmap2> export log_dir=ukesm1-0-ll/2015/logs
(ismip6) hollyhan@nid00195:/global/cscratch1/sd/hollyhan/ismip6-ocean-forcing/bedmap2> mkdir -p $log_dir
(ismip6) hollyhan@nid00195:/global/cscratch1/sd/hollyhan/ismip6-ocean-forcing/bedmap2> echo "setup"
setup
(ismip6) hollyhan@nid00195:/global/cscratch1/sd/hollyhan/ismip6-ocean-forcing/bedmap2> srun -N 1 -n 1 -c 32 ismip6_ocean_forcing config.ukesm1-0-ll_2015 \
>   --model_basin=none
Extrapolate UKESM1-0-LL model results...
  Done.
(ismip6) hollyhan@nid00195:/global/cscratch1/sd/hollyhan/ismip6-ocean-forcing/bedmap2> 
(ismip6) hollyhan@nid00195:/global/cscratch1/sd/hollyhan/ismip6-ocean-forcing/bedmap2> echo "extrapolate basins"
extrapolate basins
(ismip6) hollyhan@nid00195:/global/cscratch1/sd/hollyhan/ismip6-ocean-forcing/bedmap2> for field in temperature salinity
> do
>   for basin in $(seq 1 16)
>   do
>     srun -N 1 -n 1 -c 32 ismip6_ocean_forcing config.ukesm1-0-ll_2015 \
>       --model_field=$field --model_basin=$basin \
>       >& ${log_dir}/ukesm1-0-ll_2015_${field}_basin_${basin}.log & 
>   done
>   srun -N 1 -n 1 -c 32 ismip6_ocean_forcing config.ukesm1-0-ll_2015 \
>       --model_field=$field --model_basin=open_ocean \
>       >& ${log_dir}/ukesm1-0-ll_2015_${field}_open_ocean.log & 
> done
[1] 27773
[2] 27774
[3] 27775
[4] 27776
[5] 27777
[6] 27778
[7] 27779
[8] 27780
[9] 27781
[10] 27782
[11] 27783
[12] 27784
[13] 27785
[14] 27786
[15] 27787
[16] 27788
[17] 27789
[18] 27797
[19] 27798
[20] 27799
[21] 27800
[22] 27801
[23] 27802
[24] 27803
[25] 27804
[26] 27805
[27] 27806
[28] 27807
[29] 27808
[30] 27809
[31] 27810
[32] 27811
[33] 27812
[34] 27813
(ismip6) hollyhan@nid00195:/global/cscratch1/sd/hollyhan/ismip6-ocean-forcing/bedmap2> echo "combine basins"
combine basins
(ismip6) hollyhan@nid00195:/global/cscratch1/sd/hollyhan/ismip6-ocean-forcing/bedmap2> srun -N 1 -n 1 -c 32 ismip6_ocean_forcing config.ukesm1-0-ll_2015 \
>   --model_basin=none --model_combine_basins
srun: Job 55219465 step creation temporarily disabled, retrying (Requested nodes are busy)
srun: Step created for job 55219465
Extrapolate UKESM1-0-LL model results...
Traceback (most recent call last):
  File "/global/homes/h/hollyhan/miniconda3/envs/ismip6/lib/python3.10/site-packages/xarray/backends/file_manager.py", line 199, in _acquire_with_cache_info
    file = self._cache[self._key]
  File "/global/homes/h/hollyhan/miniconda3/envs/ismip6/lib/python3.10/site-packages/xarray/backends/lru_cache.py", line 53, in __getitem__
    value = self._cache[key]
KeyError: [<class 'netCDF4._netCDF4.Dataset'>, ('/global/cscratch1/sd/hollyhan/ismip6-ocean-forcing/bedmap2/ukesm1-0-ll/2015/progress_salinity/basin15.nc',), 'r', (('clobber', True), ('diskless', False), ('format', 'NETCDF4'), ('persist', False))]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/global/homes/h/hollyhan/miniconda3/envs/ismip6/bin/ismip6_ocean_forcing", line 33, in <module>
    sys.exit(load_entry_point('ismip6-ocean-forcing', 'console_scripts', 'ismip6_ocean_forcing')())
  File "/global/u1/h/hollyhan/ismip6-antarctic-ocean-forcing/master/ismip6_ocean_forcing/__main__.py", line 66, in main
    extrapolate_model(config)
  File "/global/u1/h/hollyhan/ismip6-antarctic-ocean-forcing/master/ismip6_ocean_forcing/model/extrap.py", line 39, in extrapolate_model
    _extrap_model(config, modelFolder)
  File "/global/u1/h/hollyhan/ismip6-antarctic-ocean-forcing/master/ismip6_ocean_forcing/model/extrap.py", line 76, in _extrap_model
    extrap_horiz(config, inFileName, outFileName, fieldName, bedFileName,
  File "/global/u1/h/hollyhan/ismip6-antarctic-ocean-forcing/master/ismip6_ocean_forcing/extrap/horiz.py", line 77, in extrap_horiz
    combine_basins(outFileName, fieldName, bedmap2FileName,
  File "/global/u1/h/hollyhan/ismip6-antarctic-ocean-forcing/master/ismip6_ocean_forcing/extrap/horiz.py", line 251, in combine_basins
    ds = xarray.open_dataset(progressFileName)
  File "/global/homes/h/hollyhan/miniconda3/envs/ismip6/lib/python3.10/site-packages/xarray/backends/api.py", line 495, in open_dataset
    backend_ds = backend.open_dataset(
  File "/global/homes/h/hollyhan/miniconda3/envs/ismip6/lib/python3.10/site-packages/xarray/backends/netCDF4_.py", line 553, in open_dataset
    store = NetCDF4DataStore.open(
  File "/global/homes/h/hollyhan/miniconda3/envs/ismip6/lib/python3.10/site-packages/xarray/backends/netCDF4_.py", line 382, in open
    return cls(manager, group=group, mode=mode, lock=lock, autoclose=autoclose)
  File "/global/homes/h/hollyhan/miniconda3/envs/ismip6/lib/python3.10/site-packages/xarray/backends/netCDF4_.py", line 330, in __init__
    self.format = self.ds.data_model
  File "/global/homes/h/hollyhan/miniconda3/envs/ismip6/lib/python3.10/site-packages/xarray/backends/netCDF4_.py", line 391, in ds
    return self._acquire()
  File "/global/homes/h/hollyhan/miniconda3/envs/ismip6/lib/python3.10/site-packages/xarray/backends/netCDF4_.py", line 385, in _acquire
    with self._manager.acquire_context(needs_lock) as root:
  File "/global/homes/h/hollyhan/miniconda3/envs/ismip6/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/global/homes/h/hollyhan/miniconda3/envs/ismip6/lib/python3.10/site-packages/xarray/backends/file_manager.py", line 187, in acquire_context
    file, cached = self._acquire_with_cache_info(needs_lock)
  File "/global/homes/h/hollyhan/miniconda3/envs/ismip6/lib/python3.10/site-packages/xarray/backends/file_manager.py", line 205, in _acquire_with_cache_info
    file = self._opener(*self._args, **kwargs)
  File "src/netCDF4/_netCDF4.pyx", line 2307, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 1925, in netCDF4._netCDF4._ensure_nc_success
OSError: [Errno -101] NetCDF: HDF error: b'/global/cscratch1/sd/hollyhan/ismip6-ocean-forcing/bedmap2/ukesm1-0-ll/2015/progress_salinity/basin15.nc'
srun: error: nid00234: task 0: Exited with exit code 1
srun: launch/slurm: _step_signal: Terminating StepId=55219465.72
[1]   Done                    srun -N 1 -n 1 -c 32 ismip6_ocean_forcing config.ukesm1-0-ll_2015 --model_field=$field --model_basin=$basin 1>&${log_dir}/ukesm1-0-ll_2015_${field}_basin_${basin}.log
[2]   Done                    srun -N 1 -n 1 -c 32 ismip6_ocean_forcing config.ukesm1-0-ll_2015 --model_field=$field --model_basin=$basin 1>&${log_dir}/ukesm1-0-ll_2015_${field}_basin_${basin}.log
[3]   Done                    srun -N 1 -n 1 -c 32 ismip6_ocean_forcing config.ukesm1-0-ll_2015 --model_field=$field --model_basin=$basin 1>&${log_dir}/ukesm1-0-ll_2015_${field}_basin_${basin}.log
[4]   Done                    srun -N 1 -n 1 -c 32 ismip6_ocean_forcing config.ukesm1-0-ll_2015 --model_field=$field --model_basin=$basin 1>&${log_dir}/ukesm1-0-ll_2015_${field}_basin_${basin}.log
[5]   Done                    srun -N 1 -n 1 -c 32 ismip6_ocean_forcing config.ukesm1-0-ll_2015 --model_field=$field --model_basin=$basin 1>&${log_dir}/ukesm1-0-ll_2015_${field}_basin_${basin}.log
[6]   Done                    srun -N 1 -n 1 -c 32 ismip6_ocean_forcing config.ukesm1-0-ll_2015 --model_field=$field --model_basin=$basin 1>&${log_dir}/ukesm1-0-ll_2015_${field}_basin_${basin}.log
[7]   Done                    srun -N 1 -n 1 -c 32 ismip6_ocean_forcing config.ukesm1-0-ll_2015 --model_field=$field --model_basin=$basin 1>&${log_dir}/ukesm1-0-ll_2015_${field}_basin_${basin}.log
[8]   Done                    srun -N 1 -n 1 -c 32 ismip6_ocean_forcing config.ukesm1-0-ll_2015 --model_field=$field --model_basin=$basin 1>&${log_dir}/ukesm1-0-ll_2015_${field}_basin_${basin}.log
[9]   Done                    srun -N 1 -n 1 -c 32 ismip6_ocean_forcing config.ukesm1-0-ll_2015 --model_field=$field --model_basin=$basin 1>&${log_dir}/ukesm1-0-ll_2015_${field}_basin_${basin}.log
[10]   Done                    srun -N 1 -n 1 -c 32 ismip6_ocean_forcing config.ukesm1-0-ll_2015 --model_field=$field --model_basin=$basin 1>&${log_dir}/ukesm1-0-ll_2015_${field}_basin_${basin}.log
[11]   Done                    srun -N 1 -n 1 -c 32 ismip6_ocean_forcing config.ukesm1-0-ll_2015 --model_field=$field --model_basin=$basin 1>&${log_dir}/ukesm1-0-ll_2015_${field}_basin_${basin}.log
[12]   Done                    srun -N 1 -n 1 -c 32 ismip6_ocean_forcing config.ukesm1-0-ll_2015 --model_field=$field --model_basin=$basin 1>&${log_dir}/ukesm1-0-ll_2015_${field}_basin_${basin}.log
[13]   Done                    srun -N 1 -n 1 -c 32 ismip6_ocean_forcing config.ukesm1-0-ll_2015 --model_field=$field --model_basin=$basin 1>&${log_dir}/ukesm1-0-ll_2015_${field}_basin_${basin}.log
[14]   Done                    srun -N 1 -n 1 -c 32 ismip6_ocean_forcing config.ukesm1-0-ll_2015 --model_field=$field --model_basin=$basin 1>&${log_dir}/ukesm1-0-ll_2015_${field}_basin_${basin}.log
[15]   Done                    srun -N 1 -n 1 -c 32 ismip6_ocean_forcing config.ukesm1-0-ll_2015 --model_field=$field --model_basin=$basin 1>&${log_dir}/ukesm1-0-ll_2015_${field}_basin_${basin}.log
[16]   Done                    srun -N 1 -n 1 -c 32 ismip6_ocean_forcing config.ukesm1-0-ll_2015 --model_field=$field --model_basin=$basin 1>&${log_dir}/ukesm1-0-ll_2015_${field}_basin_${basin}.log
[17]   Done                    srun -N 1 -n 1 -c 32 ismip6_ocean_forcing config.ukesm1-0-ll_2015 --model_field=$field --model_basin=open_ocean 1>&${log_dir}/ukesm1-0-ll_2015_${field}_open_ocean.log
[18]   Done                    srun -N 1 -n 1 -c 32 ismip6_ocean_forcing config.ukesm1-0-ll_2015 --model_field=$field --model_basin=$basin 1>&${log_dir}/ukesm1-0-ll_2015_${field}_basin_${basin}.log
[19]   Done                    srun -N 1 -n 1 -c 32 ismip6_ocean_forcing config.ukesm1-0-ll_2015 --model_field=$field --model_basin=$basin 1>&${log_dir}/ukesm1-0-ll_2015_${field}_basin_${basin}.log
[20]   Done                    srun -N 1 -n 1 -c 32 ismip6_ocean_forcing config.ukesm1-0-ll_2015 --model_field=$field --model_basin=$basin 1>&${log_dir}/ukesm1-0-ll_2015_${field}_basin_${basin}.log
[21]   Done                    srun -N 1 -n 1 -c 32 ismip6_ocean_forcing config.ukesm1-0-ll_2015 --model_field=$field --model_basin=$basin 1>&${log_dir}/ukesm1-0-ll_2015_${field}_basin_${basin}.log
[22]   Done                    srun -N 1 -n 1 -c 32 ismip6_ocean_forcing config.ukesm1-0-ll_2015 --model_field=$field --model_basin=$basin 1>&${log_dir}/ukesm1-0-ll_2015_${field}_basin_${basin}.log
[23]   Done                    srun -N 1 -n 1 -c 32 ismip6_ocean_forcing config.ukesm1-0-ll_2015 --model_field=$field --model_basin=$basin 1>&${log_dir}/ukesm1-0-ll_2015_${field}_basin_${basin}.log
[24]   Done                    srun -N 1 -n 1 -c 32 ismip6_ocean_forcing config.ukesm1-0-ll_2015 --model_field=$field --model_basin=$basin 1>&${log_dir}/ukesm1-0-ll_2015_${field}_basin_${basin}.log
[25]   Done                    srun -N 1 -n 1 -c 32 ismip6_ocean_forcing config.ukesm1-0-ll_2015 --model_field=$field --model_basin=$basin 1>&${log_dir}/ukesm1-0-ll_2015_${field}_basin_${basin}.log
[26]   Done                    srun -N 1 -n 1 -c 32 ismip6_ocean_forcing config.ukesm1-0-ll_2015 --model_field=$field --model_basin=$basin 1>&${log_dir}/ukesm1-0-ll_2015_${field}_basin_${basin}.log
[27]   Done                    srun -N 1 -n 1 -c 32 ismip6_ocean_forcing config.ukesm1-0-ll_2015 --model_field=$field --model_basin=$basin 1>&${log_dir}/ukesm1-0-ll_2015_${field}_basin_${basin}.log
[28]   Done                    srun -N 1 -n 1 -c 32 ismip6_ocean_forcing config.ukesm1-0-ll_2015 --model_field=$field --model_basin=$basin 1>&${log_dir}/ukesm1-0-ll_2015_${field}_basin_${basin}.log
[29]   Done                    srun -N 1 -n 1 -c 32 ismip6_ocean_forcing config.ukesm1-0-ll_2015 --model_field=$field --model_basin=$basin 1>&${log_dir}/ukesm1-0-ll_2015_${field}_basin_${basin}.log
[30]   Done                    srun -N 1 -n 1 -c 32 ismip6_ocean_forcing config.ukesm1-0-ll_2015 --model_field=$field --model_basin=$basin 1>&${log_dir}/ukesm1-0-ll_2015_${field}_basin_${basin}.log
[31]   Done                    srun -N 1 -n 1 -c 32 ismip6_ocean_forcing config.ukesm1-0-ll_2015 --model_field=$field --model_basin=$basin 1>&${log_dir}/ukesm1-0-ll_2015_${field}_basin_${basin}.log
[32]   Done                    srun -N 1 -n 1 -c 32 ismip6_ocean_forcing config.ukesm1-0-ll_2015 --model_field=$field --model_basin=$basin 1>&${log_dir}/ukesm1-0-ll_2015_${field}_basin_${basin}.log
[33]-  Done                    srun -N 1 -n 1 -c 32 ismip6_ocean_forcing config.ukesm1-0-ll_2015 --model_field=$field --model_basin=$basin 1>&${log_dir}/ukesm1-0-ll_2015_${field}_basin_${basin}.log
[34]+  Done                    srun -N 1 -n 1 -c 32 ismip6_ocean_forcing config.ukesm1-0-ll_2015 --model_field=$field --model_basin=open_ocean 1>&${log_dir}/ukesm1-0-ll_2015_${field}_open_ocean.log
(ismip6) hollyhan@nid00195:/global/cscratch1/sd/hollyhan/ismip6-ocean-forcing/bedmap2> vi ukesm1-0-ll/2015/logs/ukesm1-0-ll_2015_salinity_basin_15.log
(ismip6) hollyhan@nid00195:/global/cscratch1/sd/hollyhan/ismip6-ocean-forcing/bedmap2> 

```

**Comment by xylar** [comment]
Okay, that's a mystery.  The only way forward is to delete the corrupted file and run that step again.  All the steps will finish without doing anything if the output file already exists.  Why that file got corrupted is a real mystery.  Maybe 2 processes are creating the file at the same time?  Did you maybe run the job twice at the same time or something?  Just thinking of possibilities.  Or maybe did I mess things up and 2 processes both extrapolate the same field and basin?

**Comment by xylar** [comment]
@hollyhan, I see, that sounds very likely.  Killing the job in the middle of writing a file would mess things up.  It's hard to detect an incomplete file so I don't try, I assume any file that exists is fine.

That makes me thing things might work fine from a clean start.  Could you delete the `progress` directories in `ukesm-0-ll/2015` and try again (or run a different year)?

**Comment by hollyhan** [comment]
@xylar, I ran the code again from a clean start for year`2015` again as well as a different year `2011` - it all worked fine as expected! My bad for confusing us. I wouldn't have run into the problem had I run the code by submitting a job script rather than running it in the interactive mode. 

I think the changes are good to be merged!

**Review by hollyhan — APPROVED** [review]
Everything is looking great, and I also checked that the new tests that @xylar performed works correctly for me as well.

**Comment by xylar** [comment]
Thanks @hollyhan!  I'm going to merge this with the understanding that we can always make tweaks later if we find problems.

**Pull request merged**
